CREATE TABLE IF NOT EXISTS micromgr_tasks (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workflow_agent_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    evidence_type TEXT NOT NULL DEFAULT 'PHOTO',
    recurrence_type TEXT NOT NULL DEFAULT 'DAILY',
    recurrence_interval INTEGER,
    scheduled_times_json TEXT NOT NULL DEFAULT '[]',
    timezone TEXT NOT NULL DEFAULT 'UTC',
    acceptance_rules_json TEXT NOT NULL DEFAULT '[]',
    sample_evidence_url TEXT NOT NULL DEFAULT '',
    required_items_json TEXT NOT NULL DEFAULT '[]',
    scoring_enabled INTEGER NOT NULL DEFAULT 1,
    passing_score INTEGER NOT NULL DEFAULT 70,
    grace_minutes INTEGER NOT NULL DEFAULT 15,
    resubmission_allowed INTEGER NOT NULL DEFAULT 1,
    report_time TEXT NOT NULL DEFAULT '18:00',
    report_frequency TEXT NOT NULL DEFAULT 'DAILY',
    report_day_of_week INTEGER,
    report_day_of_month INTEGER,
    shift_enabled INTEGER NOT NULL DEFAULT 0,
    escalation_timeout_min INTEGER NOT NULL DEFAULT 60,
    delivery_config_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (workflow_agent_id) REFERENCES workflow_agents(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS micromgr_workers (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workflow_agent_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    name TEXT NOT NULL,
    platform TEXT NOT NULL,
    external_id TEXT NOT NULL,
    connection_id TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'worker',
    shift_start TEXT,
    shift_end TEXT,
    status TEXT NOT NULL DEFAULT 'onboarding',
    active_flag_count INTEGER NOT NULL DEFAULT 0,
    total_flag_count INTEGER NOT NULL DEFAULT 0,
    last_flagged_at TEXT,
    last_flag_reason TEXT,
    risk_level TEXT NOT NULL DEFAULT 'healthy',
    onboarded_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (workflow_agent_id) REFERENCES workflow_agents(id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES micromgr_tasks(id) ON DELETE CASCADE,
    UNIQUE (task_id, platform, external_id)
);

CREATE TABLE IF NOT EXISTS micromgr_submissions (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workflow_agent_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    worker_id TEXT NOT NULL,
    due_at TEXT NOT NULL,
    submitted_at TEXT,
    image_url TEXT NOT NULL DEFAULT '',
    raw_message TEXT NOT NULL DEFAULT '',
    ai_score INTEGER,
    ai_findings_json TEXT NOT NULL DEFAULT '[]',
    ai_feedback TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending',
    vet_attempts INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (workflow_agent_id) REFERENCES workflow_agents(id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES micromgr_tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (worker_id) REFERENCES micromgr_workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS micromgr_submission_items (
    id TEXT PRIMARY KEY,
    submission_id TEXT NOT NULL,
    label TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    evidence_type TEXT NOT NULL DEFAULT '',
    image_url TEXT NOT NULL DEFAULT '',
    raw_message TEXT NOT NULL DEFAULT '',
    received_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (submission_id) REFERENCES micromgr_submissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS micromgr_flags (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workflow_agent_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    worker_id TEXT NOT NULL,
    submission_id TEXT,
    reason_type TEXT NOT NULL,
    reason_label TEXT NOT NULL DEFAULT '',
    details TEXT NOT NULL DEFAULT '',
    severity TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    supervisor_id TEXT,
    supervisor_notified_at TEXT,
    admin_notified_at TEXT,
    resolved_at TEXT,
    resolved_by TEXT NOT NULL DEFAULT '',
    resolution_note TEXT NOT NULL DEFAULT '',
    dedupe_key TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (workflow_agent_id) REFERENCES workflow_agents(id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES micromgr_tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (worker_id) REFERENCES micromgr_workers(id) ON DELETE CASCADE,
    UNIQUE (dedupe_key)
);

CREATE TABLE IF NOT EXISTS micromgr_reports (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workflow_agent_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    cycle_key TEXT NOT NULL DEFAULT '',
    summary_markdown TEXT NOT NULL DEFAULT '',
    total_submissions INTEGER NOT NULL DEFAULT 0,
    missed_count INTEGER NOT NULL DEFAULT 0,
    avg_score REAL,
    pass_rate REAL,
    delivered_at TEXT,
    delivered_to_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (workflow_agent_id) REFERENCES workflow_agents(id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES micromgr_tasks(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_micromgr_tasks_agent ON micromgr_tasks(workflow_agent_id, status);
CREATE INDEX IF NOT EXISTS idx_micromgr_workers_lookup ON micromgr_workers(workflow_agent_id, platform, external_id);
CREATE INDEX IF NOT EXISTS idx_micromgr_submissions_due ON micromgr_submissions(task_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_micromgr_flags_open ON micromgr_flags(workflow_agent_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_micromgr_reports_task ON micromgr_reports(task_id, created_at);
